const THREAD = {
  POST: 'THREAD_POST',
  PUT: 'THREAD_REPORT',
  GET: 'THREAD_GET',
  REMOVE: 'THREAD_REMOVE',
  LOAD: 'THREAD_LOAD',
  LOAD_SUCCESS: 'THREADS_LOAD_SUCCESS',
  LOAD_SUCCESS_ONE: 'THREAD_LOAD_SUCCESS',
  LOAD_FAIL: 'THREAD_LOAD_FAIL:',
};

const REPLY = {
  POST: 'REPLY_POST',
  PUT: 'REPLY_PUT',
  GET: 'REPLY_GET',
  REMOVE: 'REPLY_REMOVE',
  LOAD: 'REPLY_LOAD',
  LOAD_SUCCESS: 'REPLY_LOAD_SUCCESS',
  LOAD_FAIL: 'REPLY_LOAD_FAIL:',
};

export { THREAD, REPLY };
