const THREAD = {
  POST: 'THREAD_POST',
  PUT: 'THREAD_REPORT',
  GET: 'THREAD_GET',
  DELETE: 'THREAD_DELETE',
  LOAD: 'THREAD_LOAD',
  LOAD_SUCCESS: 'THREADS_LOAD_SUCCESS',
  LOAD_SUCCESS_ONE: 'THREAD_LOAD_SUCCESS',
  LOAD_FAIL: 'THREAD_LOAD_FAIL:',
};

const REPLY = {
  POST: 'REPLY_POST',
  PUT: 'REPLY_PUT',
  GET: 'REPLY_GET',
  DELETE: 'REPLY_DELETE',
  LOAD: 'REPLY_LOAD',
  LOAD_SUCCESS: 'REPLY_LOAD_SUCCESS',
  LOAD_FAIL: 'REPLY_LOAD_FAIL:',
  SET_DELETE: 'REPLY_SET_DELETE',
  SET_POST: 'REPLY_SET_POST',
};

const BOARD = {
  GET: 'BOARD_GET',
  SET: 'BOARD_SET',
};

const NOTIFICATION = 'NOTIFICATION';
const CLEAR_ERROR = 'CLEAR_ERROR';

export { THREAD, REPLY, CLEAR_ERROR, NOTIFICATION, BOARD };
